CREATE TABLE contact (
  id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name             VARCHAR2(100) NOT NULL,
  phone_number     VARCHAR2(15),
  date_of_creation DATE          NOT NULL
);
